### ISSUE TITLE
Range Slider

### ISSUE THREAD

**Issue by s2t2** [jaywilz/react-bootstrap-range-slider#11]
Hi, thanks for these sliders - I like the simple and bold aesthetic. 

This is more of a feature request or question than a bug. When I think of a slider it has one nob. When I think of a range slider, it has two nobs (one representing a min value and the other representing a max value). Like this:

<img width="253" alt="Screen Shot 2020-10-09 at 11 11 26 PM" src="https://user-images.githubusercontent.com/1328807/95644644-045c8600-0a86-11eb-9880-18ad21c1a826.png">

I tried to implement a range slider like this with `react-bootstrap-range-slider` but I don't think it accepts multiple values.

Is it possible to achieve a range slider?

Here is an example of what I'm looking for:

  + http://react-component.github.io/slider/?path=/story/rc-slider--range
  + https://github.com/react-component/slider

Thanks!

**Comment by jaywilz** [comment]
Hi, I do appreciate the inclusion of "range" in the name is a point of confusion. Although selection of a range of values is not supported, the name is logically correct since the slider _does_ allow selection of a value from a range of values. The word is used in the same context as it is with [input element of type range](https://developer.mozilla.org/en-US/docs/Web/HTML/Element/input/range).

I would have gone with the name "react-bootstrap-slider" if the npm package name hadn't already been taken. Funnily enough, react-bootstrap-slider _does_ support selection of a value range / multiple handles!

Would I consider extending the component to support multiple handles in the future? Well, maybe, but the original point of the component was that it was simple, reliable and built on the HTML input element (of type range). It would be difficult to implement multiple handles without breaking this model. One possibility would be to layer multiple input elements and switch their z-indexes, possibly making use of [`mouseenter`](https://developer.mozilla.org/en-US/docs/Web/API/Element/mouseenter_event).

**Comment by s2t2** [comment]
Ok, thanks for the info. And for a great package.
